url: http://rgallaway.github.io

# Site Settings
title: Ryan Gallaway
description: "Ryan Gallaway's personal site"
keywords: "ryan, gallaway, cs, computer, science, programming"
google-tracking-id:

# Career Settings
# Default career thumbnail image.
career-img: "img/timeline/default.jpg"

exclude: ["Rakefile", "LICENSE", "readme.markdown"]
